spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: th15@rud@51th
  jpa:
    show-sql: true

stripe :
  secretKey : ${STRIPE_SECRET_KEY}
  websiteUrl :  http://localhost:4242
  webhookSecretKey: ${WEBHOOK_SECRET_KEY}